# 使用官方Python镜像作为基础镜像
FROM python:3.8-slim

# 设置工作目录
WORKDIR /app

# 复制当前目录内容到容器中的/app目录
# COPY . /app

# 安装依赖
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ \
    && pip install --no-cache-dir fastapi uvicorn edge-tts websockets pathlib

# 暴露端口
EXPOSE 8003

# 启动命令
CMD ["uvicorn", "edgeTTS_demo:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]