version: '3'
services:
  mysql:
    container_name: 'mysql5.5'
    image: 'mysql:5.5'
    ports:
      - 33060:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_PREFIX: "demo_"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    restart: unless-stopped
